# Generated by Django 4.1 on 2022-08-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("comment", models.TextField()),
                ("img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
